<?php

use Illuminate\Database\Seeder;
use Illuminate\PhpVnDataGenerator\VnBase;
use Illuminate\PhpVnDataGenerator\VnFullname;
use Illuminate\PhpVnDataGenerator\VnPersonalInfo;

class SanphamTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker    = Faker\Factory::create('vi_VN');
        $today = new DateTime('Asia/Ho_Chi_Minh');
        
        $list = [
            [ //1
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Kệ Hoa CONGRATULATION",
                'sp_gia'       => 1799000,
                'sp_hinh'      => "KeHoa_Congratulation.jpg",
                'sp_thongTin'  => "Kệ hoa gồm hoa hướng dương, hoa hồng tone vàng Đà Lạt, lan vũ nữ vàng mix cùng hoa lá phụ theo ngày. Kệ hoa sẽ là quà tặng thích hợp cho các dịp chúc mừng khai trương.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 1,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //2
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Kệ Hoa SUPER RED",
                'sp_gia'       => 2399000,
                'sp_hinh'      => "KeHoa-SuperRed.jpg",
                'sp_thongTin'  => "Kệ hoa tone đỏ rực rỡ gồm 8 hồng Ecuador đỏ nhập khẩu, lan hồ điệp trắng mix cùng hoa hồng đỏ, cẩm chướng đỏ Đà Lạt, baby, lá bạc nhập khẩu cùng hoa lá phụ theo ngày. Kệ hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng khai trương rực rỡ.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 1,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //3
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Kệ Hoa LUCKY MONEY",
                'sp_gia'       => 2599000,
                'sp_hinh'      => "KeHoa_LuckyMoney.jpg",
                'sp_thongTin'  => "Kệ hoa rực rỡ gồm lan hồ điệp sang trọng,mix cùng hoa thiên điểu, hồng hột gà, hồng môn đỏ, đồng tiền đỏ, mõm sói và hoa lá phụ trong ngày. Kệ hoa sẽ là quà tặng thích hợp cho các dịp chúc mừng khai trương thật hoành tráng và sang trọng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 1,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //4
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Giá Hoa RED PREMIUM",
                'sp_gia'       => 2599000,
                'sp_hinh'      => "GiaHoa_RedPremium.jpg",
                'sp_thongTin'  => "Kệ hoa để bàn tone đỏ rực rỡ gồm 15 hồng Ecuador đỏ nhập khẩu, mix cùng hoa hồng trắng, cát tường trắng, baby, lá bạc nhập khẩu. Kệ hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng khai trương rực rỡ.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 2,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //5
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Giá Hoa FIREWORK",
                'sp_gia'       => 2699000,
                'sp_hinh'      => "GiaHoa_FireWork.jpg",
                'sp_thongTin'  => "Kệ hoa để bàn tone vàng cam rực rỡ gồm 15 hồng Ecuador Free Spirit nhập khẩu, mix cùng hoa hồng hột gà, hồng trắng, cát tường trắng, hoa mõm sói Đà Lạt, baby, lá bạc nhập khẩu. Kệ hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng khai trương rực rỡ.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 2,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //6
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "BEST ROMANCE PLUS PASTEL",
                'sp_gia'       => 1899000,
                'sp_hinh'      => "BestRomance_Plus_Pastel.jpg",
                'sp_thongTin'  => "Kệ hoa gồm hoa hồng kem, hồng trắng hoặc cát tường trắng Đà Lạt, lan hồ điệp mix cùng hoa lá phụ theo ngày. Kệ hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4;5",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 2,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //7
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Bó dâu Mix Baby",
                'sp_gia'       => 799000,
                'sp_hinh'      => "Dau_MixBaby.jpg",
                'sp_thongTin'  => "Bó hoa dâu tây mix cùng hoa baby nhập khẩu, là bó hoa ăn được vô cùng độc đáo dành tặng người thân bạn trong các dịp sinh nhật, anniversary!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 3,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //8
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp dâu Baby",
                'sp_gia'       => 649000,
                'sp_hinh'      => "HopDau_Baby.jpg",
                'sp_thongTin'  => "Hộp hoa dâu tây mix cùng hoa baby nhập khẩu, là mẫu hoa ăn được vô cùng độc đáo dành tặng người thân bạn trong các dịp sinh nhật, anniversary!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 3,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //9
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Bó KitKat Đỏ",
                'sp_gia'       => 379000,
                'sp_hinh'      => "KitKat_Valentine.jpg",
                'sp_thongTin'  => "Bó hoa Kit Kat gồm 18 thanh Kit Kat loại truyền thống. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 4,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //10
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Baby FERRERO 7 viên",
                'sp_gia'       => 549000,
                'sp_hinh'      => "BabyFerrero_new.jpg",
                'sp_thongTin'  => "Bó hoa bé xinh gồm 7 viên Ferrero Rocher mix cùng hoa baby nhập khẩu. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 4,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //11
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Mini Pink Baby",
                'sp_gia'       => 499000,
                'sp_hinh'      => "Mini_PinkColor.jpg",
                'sp_thongTin'  => "Bó hoa sử dụng hoa baby màu hồng nhập khẩu siêu sang chảnh. Bó hoa sẽ là quà tặng “chất và độc lạ” dành tặng người thân bạn trong các dịp sinh nhật, chúc mừng, tốt nghiệp!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 5,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //12
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Mini White Baby",
                'sp_gia'       => 399000,
                'sp_hinh'      => "BabyInTheSky_2.jpg",
                'sp_thongTin'  => "Bó hoa sử dụng hoa baby trắng nhập khẩu siêu sang chảnh. Bó hoa sẽ là quà tặng “chất và độc lạ” dành tặng người thân bạn trong các dịp sinh nhật, chúc mừng, tốt nghiệp!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 5,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //13
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Giỏ Mây Blue Mix",
                'sp_gia'       => 1099000,
                'sp_hinh'      => "GioMay_Blue_mix.jpg",
                'sp_thongTin'  => "Giỏ hoa nhỏ xinh xắn gồm 4 hoa hồng Xanh Ecuador nhập khẩu, mix cùng cát tường trắng, hoa baby trắng, lá bạc, cát tường và baby phun sơn màu xanh (màu sơn chuyên dụng dành cho ngành hoa). Giỏ hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 6,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //14
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Giỏ Mây FREE SPIRIT MIX JULIET",
                'sp_gia'       => 1099000,
                'sp_hinh'      => "GioMay_FreeSpirit_mixJuliet.jpg",
                'sp_thongTin'  => "Giỏ hoa nhỏ xinh xắn gồm 2 hồng Ecuador tone cam Free Spirit, mix cùng hoa hồng David Juliet (nhập từ vườn Đà Lạt), hoa baby trắng, lá bạc, cùng hoa cát tường, baby phun sơn màu tím (màu sơn chuyên dụng dành cho ngành hoa). Giỏ hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 6,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //15
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp Baby Rainbow",
                'sp_gia'       => 949000,
                'sp_hinh'      => "HopBabyRainbow_Small.jpg",
                'sp_thongTin'  => "Hộp hoa sử dụng hoa baby màu cầu vồng nhập khẩu siêu sang chảnh, sẽ là quà tặng “chất và độc lạ” dành tặng người thân bạn trong các dịp sinh nhật, chúc mừng!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 7,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //16
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp Red Rose",
                'sp_gia'       => 749000,
                'sp_hinh'      => "3_Red_Rose_Box.jpg",
                'sp_thongTin'  => "Hộp hoa hồng đỏ đầy lãng mạn, gồm hoa hồng đỏ Đà Lạt. Hộp hoa sẽ là quà tặng thích hợp cho các dịp kỷ niệm ngày yêu nhau hoặc sinh nhật người yêu.",
                'sp_danhGia'   => "1;2;3;4;5",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 7,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //17
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hoa MESSENGER - SUMMER MIX",
                'sp_gia'       => 449000,
                'sp_hinh'      => "HoaVietTay_SummerMix.jpg",
                'sp_thongTin'  => "Bó hoa gồm hướng dương xinh xắn và dòng chữ viết tay trên bó hoa, sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 8,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //18
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hoa MESSENGER - SPRING MIX",
                'sp_gia'       => 449000,
                'sp_hinh'      => "HoaMessenger_SpringMix_GoodDay_2.jpg",
                'sp_thongTin'  => "Bó hoa gồm hoa hồng kem, hồng sen, cẩm chướng hồng Đà Lạt cùng dòng chữ xinh xắn, sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 8,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //19
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hồng Kem Baby",
                'sp_gia'       => 649000,
                'sp_hinh'      => "HongKemBaby.jpg",
                'sp_thongTin'  => "Bó hoa Hồng Kem Baby gồm hoa hồng kem Đà Lạt mix cùng baby và lá bạc nhập khẩu. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 9,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //20
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Chậu BABY RAINBOW XMAS TREE MIX Trái Châu Đỏ",
                'sp_gia'       => 999000,
                'sp_hinh'      => "Chau_Xmas_BabyRainbow_DenLed_2.jpg",
                'sp_thongTin'  => "Chậu hoa sử dụng hoa baby màu cầu vồng nhập khẩu siêu sang chảnh mix cùng trái châu đỏ trang trí, cắm hình cây thông Noel siêu xinh, sẽ là quà tặng “chất và độc lạ” dành tặng người thân bạn trong mùa Noel này!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 10,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //21
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "RED ECUADOR 10B MIX BABY",
                'sp_gia'       => 1399000,
                'sp_hinh'      => "RedEcuadormixBaby_mixBlackPaper.jpg",
                'sp_thongTin'  => "Bó hoa gồm 10 hồng Ecuador đỏ mix cùng baby trắng nhập khẩu. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 11,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //22
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp hoa HAPPY OPENING",
                'sp_gia'       => 999000,
                'sp_hinh'      => "HopHoa_HuongDuongMix.jpg",
                'sp_thongTin'  => "Hộp hoa gồm hướng dương, hồng kem Đà Lạt mix cùng hoa lá phụ theo ngày. Hộp hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 12,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //23
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hoa cưới Baby Day",
                'sp_gia'       => 799000,
                'sp_hinh'      => "HoaCuoiBaby.jpg",
                'sp_thongTin'  => "Hoa cưới baby trắng giản dị mà sang trọng. Mỗi bó hoa cưới sẽ được Happy Flower tặng kèm 1 hoa cài áo chú rể cùng tone màu bạn nhé!",
                'sp_danhGia'   => "1;2;3;4;5",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 13,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //24
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hoa cưới Happy Ending",
                'sp_gia'       => 899000,
                'sp_hinh'      => "HappyEnding.jpg",
                'sp_thongTin'  => "Bó hoa cưới lãng mạn gồm hồng kem, mix hồng trắng, baby và lá bạc. Mỗi bó hoa cưới sẽ được tặng kèm 1 hoa cài áo chú rể cùng tone màu.",
                'sp_danhGia'   => "1;2;3;4;5",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 13,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //25
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Bó gòn tốt nghiệp 3 viên MIX BABY Xanh",
                'sp_gia'       => 699000,
                'sp_hinh'      => "Bo_Gon_TotNghiep_3V_BabyXanh.jpg",
                'sp_thongTin'  => "Bó hoa kẹo bông gòn gồm 3 viên kẹo bông gòn mix cùng hoa baby màu xanh độc đáo, sẽ là quà tặng thích hợp cho dịp chúc mừng tốt nghiệp.",
                'sp_danhGia'   => "1;2;3;4;5",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 14,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //26
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Kệ hoa chia buồn FULL trắng",
                'sp_gia'       => 1399000,
                'sp_hinh'      => "KeHoaChiaBuon_FullTrang.jpg",
                'sp_thongTin'  => "Kệ hoa chia buồn tone trắng, được kết từ hoa cúc đại trắng, thay lời chia buồn chân thành và trang trọng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 15,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //27
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Kệ hoa chia buồn LAST GOODBYE",
                'sp_gia'       => 2799000,
                'sp_hinh'      => "KeHoa_LastGoodbye-1.jpg",
                'sp_thongTin'  => "Kệ hoa chia buồn mix cùng lan hồ điệp sang trọng, thay lời chia buồn chân thành và trang trọng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 15,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //28
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp Thỏ FERRERO BABY MIX Hồng Da",
                'sp_gia'       => 799000,
                'sp_hinh'      => "HopFerrero_mixHong_vaBaby.jpg",
                'sp_thongTin'  => "Hộp hoa thỏ cưng gồm 7 viên chocolate Ferrero Rocher mix cùng hoa hồng kem Đà Lạt và baby nhập khẩu. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 16,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //29
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp Bé Heo PING PONG MIX BABY",
                'sp_gia'       => 849000,
                'sp_hinh'      => "Hop_PingPongBeHeo_Baby_2.jpg",
                'sp_thongTin'  => "Hộp hoa các bé heo siêu đáng yêu, kết từ hoa ping pong trắng, baby hồng nhập khẩu, sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng bạn nhé!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 16,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //30
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Bó PING PONG Sáp MINION 3B",
                'sp_gia'       => 549000,
                'sp_hinh'      => "Bo_HoaPingPongSap_Minion_3b.jpg",
                'sp_thongTin'  => "Bó hoa hình Minion siêu cute được kết từ hoa Ping Pong SÁP, mix cùng baby trắng, sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng bạn nhé!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 17,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //31
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Bó hoa khô - Cẩm tú cầu hồng nhạt",
                'sp_gia'       => 449000,
                'sp_hinh'      => "CTC_Kho_1b.jpg",
                'sp_thongTin'  => "Bó hoa khô cẩm tú cầu màu hồng xinh xắn, độ bền từ 3-6 tháng trong nhiệt độ bình thường 23-27 độ (tránh ánh nắng trực tiếp và môi trường ẩm ướt).",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 18,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //32
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hoa ECUADOR FREE SPIRIT",
                'sp_gia'       => 849000,
                'sp_hinh'      => "FreeSpirit_5b.jpg",
                'sp_thongTin'  => "Bó hoa gồm 5 hồng Ecuador Free Spirit mix cùng lá bạc nhập khẩu. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 19,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //33
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hoa ECUADOR FANCY CAKE",
                'sp_gia'       => 1399000,
                'sp_hinh'      => "FancyCakemixBlackPaper.jpg",
                'sp_thongTin'  => "Bó hoa gồm 10 hoa hồng Ecuador Fancy Cake mix lá bạc nhập khẩu. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 19,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //34
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "SUNNY DAY",
                'sp_gia'       => 499000,
                'sp_hinh'      => "SunnyDay_399.jpg",
                'sp_thongTin'  => "Bó hoa gồm 4 hoa hướng dương mix cùng hoa thạch thảo. Bó hoa sẽ là quà tặng thích hợp cho các dịp sinh nhật, chúc mừng tốt nghiệp.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 20,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //35
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Chậu Lan Hồ Điệp 3 Cành Trắng",
                'sp_gia'       => 897000,
                'sp_hinh'      => "Lan_3canhTrang_giayLua_XanhNgoc.jpg",
                'sp_thongTin'  => "Chậu lan hồ điệp 3 cành sang trọng, màu lan: Trắng. Chậu lan được trang trí với giấy lụa màu xanh ngọc, sẽ là món quà đặc biệt dành cho người thân bạn trong các dịp Tết, sinh nhật, chúc mừng khai trương.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 21,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //36
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Chậu Lan Hồ Điệp 6 Cành Vàng",
                'sp_gia'       => 1894000,
                'sp_hinh'      => "Lan_6Canh_Vang_Luxury_VaiVang.jpg",
                'sp_thongTin'  => "Chậu lan hồ điệp 6 cành sang trọng, màu lan: vàng loại mini. Chậu lan được bọc vải tone màu vàng rực rỡ, sẽ là món quà đặc biệt dành cho người thân bạn trong các dịp Tết, chúc mừng khai trương.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 21,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //37
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp Gòn Trái Cây",
                'sp_gia'       => 349000,
                'sp_hinh'      => "Hop_Gon_MuiVi.jpg",
                'sp_thongTin'  => "Hộp kẹo bông gòn gồm 4 viên kẹo bông gòn vị trái cây (Vải, Dâu, Chuối, Cam), sẽ là quà tặng thích hợp cho dịp sinh nhật, tặng bạn gái.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 22,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //38
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Bó Gòn SUPER",
                'sp_gia'       => 599000,
                'sp_hinh'      => "SuperGon_WhitePaper.jpg",
                'sp_thongTin'  => "Bó hoa kẹo bông gòn gồm 6 viên kẹo bông gòn đủ màu sắc như hình, sẽ là quà tặng thích hợp cho dịp chúc mừng tốt nghiệp.",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 22,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
            [ //39
                'sp_ma'        => $faker->ean8,
                'sp_ten'       => "Hộp Gòn 3 Viên HALLOWEEN MIX BABY WHITE",
                'sp_gia'       => 799000,
                'sp_hinh'      => "HopGon_3v_Halloween_2.jpg",
                'sp_thongTin'  => "Hộp hoa gồm 3 viên kẹo bông gòn dễ thương phiên bản dành riêng cho Halloween, mix cùng hoa baby nhập khẩu, sẽ là quà tặng thích hợp cho dịp Halloween năm nay bạn nhé!",
                'sp_danhGia'   => "1;2;3;4",
                'sp_taoMoi'    => $today->format('Y-m-d H:i:s'),
                'sp_capNhat'   => $today->format('Y-m-d H:i:s'),
                'sp_trangThai' => 2,
                'l_id'         => 22,
                'ncc_id'       => $faker->numberBetween(1, 5),
            ],
        ];

        DB::table('home_sanpham')->insert($list);
    }
}
